export const userList = [
  {
    id: 1,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 2,
    name: "Avinash",
    email: "avinash@gmail.com",
    age: 24,
    address: "Bangalore",
  },
  {
    id: 3,
    name: "Deepak Sharma",
    email: "deepaksharma@gmail.com",
    age: 25,
    address: "Ghazipur",
  },
  {
    id: 4,
    name: "Satyam Singh",
    email: "satyamsingh@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 5,
    name: "Deepak Sharma",
    email: "deepaksharma@gmail.com",
    age: 25,
    address: "Ghazipur",
  },
  {
    id: 6,
    name: "Satyam Singh",
    email: "satyamsingh@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 7,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 8,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 9,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 10,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 11,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 12,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
  {
    id: 13,
    name: "krishna kumar",
    email: "krishnakushwaha743@gmail.com",
    age: 25,
    address: "Varanasi",
  },
];
